
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DI-SONIC
 */
public class hall extends javax.swing.JFrame {

    /**
     * Creates new form hall
     *
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;

    public hall() {
        super("Hall");
        initComponents();

        conn = (com.mysql.jdbc.Connection) databaseconnection.getConnection();
        showrecord();
    }

    class jPanelGradiant extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color colour1 = new Color(1, 100, 100);
            Color colour2 = new Color(106, 180, 211);
            GradientPaint gp = new GradientPaint(0, 0, colour1, 180, height, colour2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);

        }
    }

    public void showrecord() {

        try {
            stmt = conn.createStatement();
            String sql = "SELECT * FROM hall";
            ResultSet res = stmt.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

            stmt = conn.createStatement();
            String sql1 = "SELECT * FROM timetable1";
            ResultSet res1 = stmt.executeQuery(sql1);
            jTable2.setModel(DbUtils.resultSetToTableModel(res1));

        } catch (Exception e) {
            JOptionpane.showmessgeDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGradiant();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        hcpa = new javax.swing.JTextField();
        hidTextFeild = new javax.swing.JTextField();
        hname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submit_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        dateTextFeild = new javax.swing.JTextField();
        TT_NoTextFeild = new javax.swing.JTextField();
        timeTextFeild = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        hfee = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        subidTextFeild = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        submit_button1 = new javax.swing.JButton();
        update_button1 = new javax.swing.JButton();
        delete_button1 = new javax.swing.JButton();
        tidTextFeild = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(207, 217, 223));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hall Manegement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(204, 0, 0))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Hall ID");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Hall Name");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("Hall Capacity");

        submit_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        update_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        delete_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        back_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("TimeTable");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        timeTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextFeildActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Tno");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Time");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("Date");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setText("Tid");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setShowGrid(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setText("Hall fee");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel11.setText("SubNo");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Hall Records");

        submit_button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        submit_button1.setText("Submit");
        submit_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_button1ActionPerformed(evt);
            }
        });

        update_button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        update_button1.setText("Update");
        update_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_button1ActionPerformed(evt);
            }
        });

        delete_button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        delete_button1.setText("Delete");
        delete_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel1))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hname, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hidTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hfee, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TT_NoTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(timeTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tidTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subidTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hcpa, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(submit_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(update_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel4))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(701, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(45, 45, 45)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hidTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hcpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submit_button)
                            .addComponent(update_button)
                            .addComponent(delete_button))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TT_NoTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dateTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timeTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subidTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tidTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(submit_button1)
                                    .addComponent(update_button1)
                                    .addComponent(delete_button1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(back_button)))
                        .addGap(77, 77, 77))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel10)
                    .addContainerGap(479, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Info");

        jMenuItem2.setText("About Us");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(918, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // Submit button code:

        try {

            stmt = conn.createStatement();

            String Hcapa = hcpa.getText();
            String Hname = hname.getText();
            String HFee = hfee.getText();

            if (Hname.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please insert Data");

            } else {

                String sql = "INSERT INTO HALL (h_name, capacity, hall_fee) values ('" + Hname + "','" + Hcapa + "','" + HFee + "')";
                int stmtd = stmt.executeUpdate(sql);
                if (stmtd == 1) {
                    JOptionPane.showMessageDialog(null, "Data Insert Successfull");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Insert Not Successfull");
                }

            }

            hcpa.setText("");
            hidTextFeild.setText("");
            hname.setText("");
            hfee.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        setVisible(false);
        hall object = new hall();
        object.setVisible(true);


    }//GEN-LAST:event_submit_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // Update button code:

        try {
            stmt = conn.createStatement();
            // int stid = Integer.parseInt(id.getText());

            String Hcapa = hcpa.getText();
            String Hid = hidTextFeild.getText();
            String Hname = hname.getText();
            String HFee = hfee.getText();

            if (Hid.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter the hall id ");
            } else {

                if (Hcapa.isEmpty()) {
                    Hcapa = "000000000";
                }

                String sql = "UPDATE HALL SET h_id ='" + Integer.parseInt(Hid) + "', h_name ='" + Hname + "', capacity ='" + Hcapa + "', Hall_fee ='" + Integer.parseInt(HFee) + "' WHERE h_id = '" + Integer.parseInt(Hid) + "'";
                int stmtsd = stmt.executeUpdate(sql);
                if (stmtsd == 1) {
                    JOptionPane.showMessageDialog(null, "Data update Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Data update Not Successfully");
                }
            }

            hcpa.setText("");
            hidTextFeild.setText("");
            hname.setText("");
            hfee.setText("");

        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

        setVisible(false);
        hall object = new hall();
        object.setVisible(true);

    }//GEN-LAST:event_update_buttonActionPerformed


    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // Delete button code:

        try {

            stmt = conn.createStatement();
            String Hid = hidTextFeild.getText();

            if (Hid.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Enter hall id");

            } else {
                String sql = "DELETE FROM hall WHERE h_id ='" + Hid + "' ";
                int stmte = stmt.executeUpdate(sql);
                if (stmte == 1) {
                    JOptionPane.showMessageDialog(null, "Data delete Successfully");

                } else {
                    JOptionPane.showMessageDialog(null, "No Matching ID Found");
                }

            }

            hcpa.setText("");
            hidTextFeild.setText("");
            hname.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        setVisible(false);
        hall object = new hall();
        object.setVisible(true);
    }//GEN-LAST:event_delete_buttonActionPerformed


    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        home object = new home();
        object.setVisible(true);


    }//GEN-LAST:event_back_buttonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        aboutUs object = new aboutUs();
        object.setVisible(true);


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // Search Textbox code here:

        try {
            stmt = conn.createStatement();
            String text = jTextField1.getText();
            String sql = "SELECT * FROM hall WHERE h_name LIKE '" + text + "%'";
            ResultSet res = stmt.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Got an exception!");
        }


    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        int ttno = (Integer) jTable2.getValueAt(jTable2.getSelectedRow(), 0);

        String date = (String) jTable2.getValueAt(jTable2.getSelectedRow(), 1);
        String time = (String) jTable2.getValueAt(jTable2.getSelectedRow(), 2);
        int hid = (Integer) jTable2.getValueAt(jTable2.getSelectedRow(), 3);
        int tid = (Integer) jTable2.getValueAt(jTable2.getSelectedRow(), 5);
        int subid = (Integer) jTable2.getValueAt(jTable2.getSelectedRow(), 4);

        TT_NoTextFeild.setText(ttno + "");
        dateTextFeild.setText(date);
        timeTextFeild.setText(time);
        hidTextFeild.setText(hid + "");
        tidTextFeild.setText(tid + "");
        subidTextFeild.setText(subid + "");

    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here: 

        int hidd = (Integer) jTable1.getValueAt(jTable1.getSelectedRow(), 0);

        String Hname = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 1);
        // String  = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 2);
        int Hfe = (Integer) jTable1.getValueAt(jTable1.getSelectedRow(), 3);
        String Hcpa = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 2);
        //int subid  = (Integer) jTable1.getValueAt(jTable1.getSelectedRow(), 5);

        hidTextFeild.setText(hidd + "");
        hname.setText(Hname);
        hfee.setText(Hfe + "");
        hcpa.setText(Hcpa);


    }//GEN-LAST:event_jTable1MouseClicked

    private void timeTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTextFeildActionPerformed

    private void submit_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_button1ActionPerformed
        // TODO add your handling code here:

        try {

            stmt = conn.createStatement();

            String Date = dateTextFeild.getText();
            String Time = timeTextFeild.getText();
            String tid = tidTextFeild.getText();
            String subid = subidTextFeild.getText();
            String Hid = hidTextFeild.getText();

            if (Date.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please insert Data");

            } else {

                String sql = "INSERT INTO TIMETABLE1 (Date, time, h_id, sub_no, t_id) values ('" + Date + "','" + Time + "','" + Integer.parseInt(Hid) + "','" + Integer.parseInt(subid) + "','" + Integer.parseInt(tid) + "')";
                int stmtd = stmt.executeUpdate(sql);
                if (stmtd == 1) {
                    JOptionPane.showMessageDialog(null, "Data Insert Successfull");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Insert Not Successfull");
                }

            }

            hidTextFeild.setText("");
            tidTextFeild.setText("");
            dateTextFeild.setText("");
            timeTextFeild.setText("");
            subidTextFeild.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        setVisible(false);
        hall object = new hall();
        object.setVisible(true);


    }//GEN-LAST:event_submit_button1ActionPerformed

    private void update_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_button1ActionPerformed
        // TODO add your handling code here:
        try {
            stmt = conn.createStatement();
            // int stid = Integer.parseInt(id.getText());

            String Tid = TT_NoTextFeild.getText();
            String Hid = hidTextFeild.getText();
            String Date = dateTextFeild.getText();
            String Time = timeTextFeild.getText();
            String tid = tidTextFeild.getText();
            String subid = subidTextFeild.getText();

            if (Tid.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter the id ");
            } else {

                if (Hid.isEmpty()) {
                    Hid = "000000000";
                }

                String sql = "UPDATE TIMETABLE1 SET Tno ='" + Integer.parseInt(Tid) + "', Date ='" + Date + "', Time ='" + Time + "', h_id ='" + Integer.parseInt(Hid) + "',sub_no ='" + Integer.parseInt(subid) + "',t_id ='" + Integer.parseInt(tid) + "' WHERE Tno = '" + Integer.parseInt(Tid) + "'";
                int stmtsd = stmt.executeUpdate(sql);
                if (stmtsd == 1) {
                    JOptionPane.showMessageDialog(null, "Data update Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Data update Not Successfully");
                }
            }

            TT_NoTextFeild.setText(tid);
            hidTextFeild.setText("");
            tidTextFeild.setText("");
            dateTextFeild.setText("");
            timeTextFeild.setText("");
            subidTextFeild.setText("");

        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

        setVisible(false);
        hall object = new hall();
        object.setVisible(true);


    }//GEN-LAST:event_update_button1ActionPerformed

    private void delete_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button1ActionPerformed
        // TODO add your handling code here:

        try {

            stmt = conn.createStatement();
            String Tno = TT_NoTextFeild.getText();

            if (Tno.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Enter id");

            } else {
                String sql = "DELETE FROM timetable1 WHERE h_id ='" + Tno + "' ";
                int stmte = stmt.executeUpdate(sql);
                if (stmte == 1) {
                    JOptionPane.showMessageDialog(null, "Data delete Successfully");

                } else {
                    JOptionPane.showMessageDialog(null, "No Matching ID Found");
                }

            }

            hcpa.setText("");
            hidTextFeild.setText("");
            hname.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        setVisible(false);
        hall object = new hall();
        object.setVisible(true);


    }//GEN-LAST:event_delete_button1ActionPerformed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TT_NoTextFeild;
    private javax.swing.JButton back_button;
    private javax.swing.JTextField dateTextFeild;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton delete_button1;
    private javax.swing.JTextField hcpa;
    private javax.swing.JTextField hfee;
    private javax.swing.JTextField hidTextFeild;
    private javax.swing.JTextField hname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField subidTextFeild;
    private javax.swing.JButton submit_button;
    private javax.swing.JButton submit_button1;
    private javax.swing.JTextField tidTextFeild;
    private javax.swing.JTextField timeTextFeild;
    private javax.swing.JButton update_button;
    private javax.swing.JButton update_button1;
    // End of variables declaration//GEN-END:variables
}
